# REGular EXpression - INTRO TO REGEX

In [5]:
# Import the library!
import re

1. `re.search`: Finds the first match and returns it;
2. `re.findall`: Returns a list with all matches;
4. `re.sub`: Replaces a pattern with a string.

Visualizando REGEXs: https://regexper.com/

## `findall()` Function

In [7]:
text = 'My neighbor, mr. Paw, has 5 dogs and each has 10 neighbors.'
pattern = 'neighbor'

re.findall(pattern, text)

['neighbor', 'neighbor']

In [8]:
text = 'My neighbor, mr. Dog, has 5 dogs.'
pattern = 'nei'

re.findall(pattern, text)

['nei']

In [21]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern_2 = 'NEIGHBOR'

re.findall(pattern_2, text)

[]

In [11]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern_3 = 'e'

re.findall(pattern_3, text)

['e', 'e', 'e']

### Application I

In [12]:
# Extrair todas as colunas da T1
lista_colunas = ['T1_id', 'T1_nome', 'T1_id_fatura', 'T1_cd_sku', 'T2_cd_promo', 'T3_qt_vendido', 'T4_vl_total', 
                 'T5_vl_custo', 'T1_tipo_frete', 'T1_rua', 'T1_num', 'T1_cep', 'T1_cidade', 'T1_uf',
                 'T1_vl_frete', 'T2_tp_promo', 'T3_vl_promo', 'T4_vl_sv', 'T5_qt_doado']


In [13]:
' '.join(lista_colunas)

'T1_id T1_nome T1_id_fatura T1_cd_sku T2_cd_promo T3_qt_vendido T4_vl_total T5_vl_custo T1_tipo_frete T1_rua T1_num T1_cep T1_cidade T1_uf T1_vl_frete T2_tp_promo T3_vl_promo T4_vl_sv T5_qt_doado'

In [15]:
len(re.findall('T1_', ' '.join(lista_colunas)))

11

In [16]:
lista_colunas

['T1_id',
 'T1_nome',
 'T1_id_fatura',
 'T1_cd_sku',
 'T2_cd_promo',
 'T3_qt_vendido',
 'T4_vl_total',
 'T5_vl_custo',
 'T1_tipo_frete',
 'T1_rua',
 'T1_num',
 'T1_cep',
 'T1_cidade',
 'T1_uf',
 'T1_vl_frete',
 'T2_tp_promo',
 'T3_vl_promo',
 'T4_vl_sv',
 'T5_qt_doado']

In [22]:
lista_t1 = []

for coluna in lista_colunas:
    pattern = 'T1_'
    
    if re.findall(pattern, coluna):
        lista_t1.append(coluna)
        
print(lista_t1)

['T1_id', 'T1_nome', 'T1_id_fatura', 'T1_cd_sku', 'T1_tipo_frete', 'T1_rua', 'T1_num', 'T1_cep', 'T1_cidade', 'T1_uf', 'T1_vl_frete']


In [20]:
lista_ex = [1]

if lista_ex:
  print('List is not empty')
else:
  print('List is empty')

List is not empty


## Complex Patterns

### Operator '|' - OR

In [28]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern = 'dog|paw|each'
re.findall(pattern, text)

['dog', 'each', 'paw']

Selecting T1 or T4 columns:

In [30]:
lista_colunas = ['T1_id', 'T1_nome', '       T1_id_fatura', 'T1_cd_sku', 'T2_cd_promo', 'T3_qt_vendido', 'T4_vl_total', 
                 'T5_vl_custo', 'T1_tipo_frete', 'T1_rua', '  T1_num', '    T1_cep', 'T1_cidade', 'T1_uf',
                 'T1_vl_frete', '     T2_tp_promo4', '  T3_vl_promo1', 'T4_vl_sv', 'T5_qt_doado']

In [33]:
pattern = 'T1|T4|_vl_'
colunas_final = []

for coluna in lista_colunas:
    if re.findall(pattern, coluna):
        colunas_final.append(coluna)

print(colunas_final)

['T1_id', 'T1_nome', '       T1_id_fatura', 'T1_cd_sku', 'T4_vl_total', 'T5_vl_custo', 'T1_tipo_frete', 'T1_rua', '  T1_num', '    T1_cep', 'T1_cidade', 'T1_uf', 'T1_vl_frete', '  T3_vl_promo1', 'T4_vl_sv']


### Sets

In [ ]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws.'
pattern = 'paw|dog'

re.findall(pattern, text)

In [40]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws and another Dog.'
pattern = '[Pp][Aa][Ww]|[Dd][Oo][Gg]'

re.findall(pattern, text)

['Paw', 'dog', 'paw', 'Dog']

In [41]:
text = 'Meu mEU MeUDEOS'
pattern = '[Mm][Ee][Uu]'

re.findall(pattern, text)

['Meu', 'mEU', 'MeU']

In [42]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern = '[Pp]aw'

re.findall(pattern, text)

['Paw', 'paw']

In [44]:
text = 'Patas pata pAta fAta fAca 2Ace 2ata'
pattern = '[pPasdf2][Aa][ct]a'

re.findall(pattern, text)

['Pata', 'pata', 'pAta', 'fAta', 'fAca', '2ata']

In [48]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern = '[Pp][Aa][Ww][,s]'

re.findall(pattern, text)

['Paw,', 'paws']

In [49]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern = '[Pp]aw|dog'
re.findall(pattern, text)

['Paw', 'dog', 'paw']

#### Application II

In [51]:
# Extrair todas as colunas da T1 ou da T2
lista_colunas = ['T1_id', 't1_nome', 'T1_id_fatura', 't1_cd_sku', 'T2_cd_promo', 'T3_qt_vendido', 'T4_vl_total', 
                 'T5_vl_custo', 'T1_tipo_frete', 'T1_rua', 'T1_num', 'T1_cep', 'T1_cidade', 't1_uf',
                 'T1_vl_frete', 't2_tp_promo', 'T3_vl_promo', 'T4_vl_sv', 'T5_qt_doado']


In [53]:
lista_colunas_T1T2 = []
pattern = '[Tt][12345]'

for coluna in lista_colunas:

    if re.findall(pattern, coluna):
        lista_colunas_T1T2.append(coluna)

print(lista_colunas_T1T2)

['T1_id', 't1_nome', 'T1_id_fatura', 't1_cd_sku', 'T2_cd_promo', 'T3_qt_vendido', 'T4_vl_total', 'T5_vl_custo', 'T1_tipo_frete', 'T1_rua', 'T1_num', 'T1_cep', 'T1_cidade', 't1_uf', 'T1_vl_frete', 't2_tp_promo', 'T3_vl_promo', 'T4_vl_sv', 'T5_qt_doado']


## `sub()` Function

In [54]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws.'
pattern = '[Pp]aw'
nova_pattern = 'Pedro'

re.sub(pattern, nova_pattern, text)

'My neighbor, mr. Pedro, has 5 dogs and each one has 4 Pedros.'

In [60]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws.'
pattern = '[.,;:]'
nova_pattern = ''

re.sub(pattern, nova_pattern, text)

'My neighbor mr Paw has 5 dogs and each one has 4 paws'

Podemos utilizar a função `sub()` para fazer a limpeza de strings semi-estruturados, por exemplo, nossa lista de colunas!

In [61]:
lista_colunas = ['T1_id', 't1_nome', 'T1_id_fatura', 't1_cd_sku', 'T2_cd_promo', 'T3_qt_vendido', 'T4_vl_total', 
                 'T5_vl_custo', 'T1_tipo_frete', 'T1_rua', 'T1_num', 'T1_cep', 'T1_cidade', 'T1_uf',
                 'T1_vl_frete', 't2_tp_promo', 'T3_vl_promo', 'T4_vl_sv', 'T5_qt_doado']

In [66]:
lista_colunas_limpa = []
pattern = '[Tt][123456789]_'
new_pattern = ''

for coluna in lista_colunas:
  new_column_name = re.sub(pattern, new_pattern, coluna)
  lista_colunas_limpa.append(new_column_name)

print(lista_colunas_limpa)

['id', 'nome', 'id_fatura', 'cd_sku', 'cd_promo', 'qt_vendido', 'vl_total', 'vl_custo', 'tipo_frete', 'rua', 'num', 'cep', 'cidade', 'uf', 'vl_frete', 'tp_promo', 'vl_promo', 'vl_sv', 'qt_doado']


## Special sets
1. `[a-z]`: any lower case letter;
1. `[A-Z]`: any upper case letter;
1. `[0-9]`: any digit;
1. `[A-Za-z]`: all letters;
1. `[À-ž]`: all diacriticals.

In [67]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern = r'[A-Za-z][A-Za-z][A-Za-z]'
re.findall(pattern, text)

['nei', 'ghb', 'Paw', 'has', 'dog', 'and', 'eac', 'one', 'has', 'paw']

In [69]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern = 'p[A-Za-zÀ-ž]ws'

re.findall(pattern, text)

['paws']

. `^` is equivalent to NOT

In [71]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws.\n'
pattern = '[^A-Za-z0-9À-ž]'

re.findall(pattern, text)

[' ',
 ',',
 ' ',
 '.',
 ' ',
 ',',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '.',
 '\n']

## Meta-characters

1. `\w`: any alpha-numerical character ([0-9a-ZA-ZÀ-ž])
3. `\d`: any digit
7. `.` : any charecter except newline - `\n`.

In [73]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'
pattern = r'\d'

print(re.findall(pattern, text))

['5', '4']


In [77]:
text = 'My neighbor, mr. Paw, has 555 dogs and each one has 4 paws'
pattern = r'\w\w\w'

print(re.findall(pattern, text))

['nei', 'ghb', 'Paw', 'has', '555', 'dog', 'and', 'eac', 'one', 'has', 'paw']


In [79]:
text = 'My neighbor\n, mr. Paw,\n has 5 dogs\n and each one has 4 paws'
pattern = r'.'

print(re.findall(pattern, text))

['M', 'y', ' ', 'n', 'e', 'i', 'g', 'h', 'b', 'o', 'r', ',', ' ', 'm', 'r', '.', ' ', 'P', 'a', 'w', ',', ' ', 'h', 'a', 's', ' ', '5', ' ', 'd', 'o', 'g', 's', ' ', 'a', 'n', 'd', ' ', 'e', 'a', 'c', 'h', ' ', 'o', 'n', 'e', ' ', 'h', 'a', 's', ' ', '4', ' ', 'p', 'a', 'w', 's']


In [80]:
print(text)

My neighbor
, mr. Paw,
 has 5 dogs
 and each one has 4 paws


In [82]:
''.join(re.findall(pattern, text))

'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws'

In [83]:
text = 'My neighbor, mr. Paw, has 555 dogs and each one has 4 paws'
pattern = r'\w\w\w'

print(re.findall(pattern, text))

['nei', 'ghb', 'Paw', 'has', '555', 'dog', 'and', 'eac', 'one', 'has', 'paw']


In [87]:
documents = [
 'My neighbor, mr. Paw, has 555 dogs and each one has 4 paws', 
 'My neighbor, mr. Paw, has dogs and each one has 4 paws', 
 'My neighbor, mr. Paw, has dogs and each one has paws'
]

In [89]:
match_lists = []
for doc in documents:
  results = re.findall(r'[0-9]', doc)
  print(results)
  if results:
    match_lists.append(doc)
print(match_lists)

['5', '5', '5', '4']
['4']
[]
['My neighbor, mr. Paw, has 555 dogs and each one has 4 paws', 'My neighbor, mr. Paw, has dogs and each one has 4 paws']


In [90]:
[doc for doc in documents if re.findall(r'[0-9]', doc)]

['My neighbor, mr. Paw, has 555 dogs and each one has 4 paws',
 'My neighbor, mr. Paw, has dogs and each one has 4 paws']

In [91]:
[re.findall(r'[0-9]', doc) for doc in documents]

[['5', '5', '5', '4'], ['4'], []]

In [92]:
[doc for doc in documents if re.findall(r'[0-9]', doc) and re.findall(r'[a-z]', doc)]

['My neighbor, mr. Paw, has 555 dogs and each one has 4 paws',
 'My neighbor, mr. Paw, has dogs and each one has 4 paws']

In [95]:
text = 'My neighbor, mr. Paw, has 555 dogs and each one has 4 paws'
pattern = r' \w\w\w\w[,. ]'

print(re.findall(pattern, text))

[' dogs ', ' each ']


In [ ]:
"pedro.teche@ironhack.com"

"[a-z][a-z]?? @ [a-z][a-z] ??? .co"

## Quantifiers
1. `*`: 0 or more;
2. `?`: 0 ou 1;
3. `+`: At least one;

In [97]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws.'
pattern = r'[A-Za-z]+'

re.findall(pattern, text)

['My',
 'neighbor',
 'mr',
 'Paw',
 'has',
 'dogs',
 'and',
 'each',
 'one',
 'has',
 'paws']

In [ ]:
text1 = 'The price of the product was R$99.99'
text2 = 'The price of the product was R$9,999.99'
text3 = 'The price of the product was R$99'
'99.99'
'9,999.99'
'99'

In [98]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws.'
pattern = r'[A-z0-9]+'

re.findall(pattern, text)

['My',
 'neighbor',
 'mr',
 'Paw',
 'has',
 '5',
 'dogs',
 'and',
 'each',
 'one',
 'has',
 '4',
 'paws']

In [102]:
text1 = 'The price of the product was R$999.47'
pattern = r'[0-9]+'

re.findall(pattern, text1)

['999', '47']

In [103]:
text = 'My neighbor, mr. Paw, has 5 dogs and each one has 4 paws.'
pattern = r'[0-9]+'

re.findall(pattern, text)

['5', '4']

## EApplication III

In [105]:
import re

str="""
>Venues
>Marketing
>medalists
>Controversies
>Paralympics
>snowboarding
>[1]
>Netherlands
>[2]
>Norway
>[10]
>[11]
>References
>edit
>[12]
>Norway
>Germany
>Canada
>Netherlands
>Japan
>Italy
>Belarus
>China
>Slovakia
<$#%#$%
<#$#$$
<**&&^^
>Slovenia
>Belgium
>Spain
>Kazakhstan
>[15]
>1964
>1968
>1972
>1992
>1996
>2000"""

pattern = r'>.+'
data=re.findall(pattern, str)

print(data)

['>Venues', '>Marketing', '>medalists', '>Controversies', '>Paralympics', '>snowboarding', '>[1]', '>Netherlands', '>[2]', '>Norway', '>[10]', '>[11]', '>References', '>edit', '>[12]', '>Norway', '>Germany', '>Canada', '>Netherlands', '>Japan', '>Italy', '>Belarus', '>China', '>Slovakia', '>Slovenia', '>Belgium', '>Spain', '>Kazakhstan', '>[15]', '>1964', '>1968', '>1972', '>1992', '>1996', '>2000']


## Application IV

In [109]:
import re

str='The advancements in biomarine studies franky@google.net with the investments necessary and Davos sinatra123@yahoo.com Then The New Yorker article on wind farms...'

pattern = r'[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z]+'
emails=re.findall(pattern, str)
print(emails)

['franky@google.net', 'sinatra123@yahoo.com']


Crie um segundo padrão para extrair apenas os domínios dos e-mails encontrados no texto (`@google.com` e `@yahoo.com`)

In [110]:
pattern = r'@[a-zA-Z0-9]+.com'
domains=re.findall(pattern, str)

print(domains)

['@yahoo.com']


## Application V

In [111]:
import re

str='''
Ancient Script 21298: The Takenouchi documents are the ancient historical records that have been secretly preserved and passed down from generation to generation by the Takenouchi family, the head of family being the chief priest of the Koso Kotai Jingu shrine. 212-111-5932 
Ancient Sword 21299: The Takenouchi swords are the ancient historical swords that have been secretly preserved and passed down from generation to generation by the Takenouchi family, the head of family being the chief priest of the Koso Kotai Jingu shrine. 212-111-5932
Ancient Jewelry 21300: The Takenouchi gems are the ancient historical jewels that have been secretly preserved and passed down from generation to generation by the Takenouchi family, the head of family being the chief priest of the Koso Kotai Jingu shrine. 212-111-5932
'''

pattern = r'212[0-9]+'
data=re.findall(pattern, str)

print(data)

['21298', '21299']


Construa outro padrão para extrair a linha completa de informação associada a cada artefato cujo ID (21298, 21299, 21300) começa com 212.

In [121]:
pattern = r'212[0-9]+.+'
data=re.findall(pattern, str)

print(data)

['Ancient Script 21298: The Takenouchi documents are the ancient historical records that have been secretly preserved and passed down from generation to generation by the Takenouchi family, the head of family being the chief priest of the Koso Kotai Jingu shrine. 212-111-5932 ', 'Ancient Sword 21299: The Takenouchi swords are the ancient historical swords that have been secretly preserved and passed down from generation to generation by the Takenouchi family, the head of family being the chief priest of the Koso Kotai Jingu shrine. 212-111-5932', 'Ancient Jewelry 21300: The Takenouchi gems are the ancient historical jewels that have been secretly preserved and passed down from generation to generation by the Takenouchi family, the head of family being the chief priest of the Koso Kotai Jingu shrine. 212-111-5932']


In [125]:
data[2]

'Ancient Jewelry 21300: The Takenouchi gems are the ancient historical jewels that have been secretly preserved and passed down from generation to generation by the Takenouchi family, the head of family being the chief priest of the Koso Kotai Jingu shrine. 212-111-5932'

In [114]:
data[1]

'21299: The Takenouchi swords are the ancient historical swords that have been secretly preserved and passed down from generation to generation by the Takenouchi family, the head of family being the chief priest of the Koso Kotai Jingu shrine. 212-111-5932'

# More Challenges!

https://www.hackerrank.com/domains/regex - Hackerrank possui toda uma trilha de aprendizagem associada à REGEX;

https://regexone.com/lesson/introduction_abcs - REGEXONE traz não apenas exercícios mas também breves lições sobre os conceitos abordados em cada ex.
